### Gets all the categories
GET {{host}}/posts/categories
Accept: application/json

### Adds the category
POST {{host}}/posts/categories
Content-Type: application/json

{
  "title": "Новости",
  "url": "News",
  "token": {{token}}
}

### Adds the category
POST {{host}}/posts/categories
Content-Type: application/json

{
  "title": "Аддоны",
  "url": "addons",
  "token": {{token}}
}