### Gets the posts
GET {{host}}/posts
Accept: application/json

### Gets the posts by category
GET {{host}}/posts/category/2
Accept: application/json

### Adds the post
POST {{host}}/posts/
Content-Type: application/json

{
  "token": {{token}},
  "title": "Мой первый пост",
  "image": "http://prestij.xyz/img.png",
  "content": "Текст новости в краткой его форме. Возможно первый абзац или что-то типо того.",
  "category_id": 1,
  "tags": ""
}

### Likes the post
POST {{host}}/posts/like
Content-Type: application/json

{
  "token": {{token}},
  "post_id": 1
}

### Unlikes the post
POST {{host}}/posts/unlike
Content-Type: application/json

{
  "token": {{token}},
  "post_id": 1
}

### Comments the post
POST {{host}}/posts/comment
Content-Type: application/json

{
  "token": {{token}},
  "post_id": 1,
  "text": "Oh, i really like it!"
}

### Removes the comment
DELETE {{host}}/posts/comment
Content-Type: application/json

{
  "token": {{token}},
  "comment_id": 1
}