### Get user by bt_id
GET http://localhost:8000/users/1
Accept: application/json

### Adds the user
POST http://localhost:8000/users/
Content-Type: application/json

{
  "bt_id": 1,
  "bt_title": "Daikiri",
  "name": "Дайкири"
}
