### Sending meta text changes
PUT {{host}}/characters/meta/Дайкирия
Content-Type: application/json

{
  "text": "144"
}


### Getting character
GET {{host}}/characters/дайкирия
Accept: application/json

### Guild activity
GET {{host}}/guild/activity
Accept: application/json