### Sending meta text changes
PUT http://localhost:8000/characters/meta/Дайкирия
Content-Type: application/json

{
  "text": "144"
}


### Getting character
GET http://localhost:8000/characters/дайкирия
Accept: application/json

### Guild activity
GET http://localhost:8000/guild/activity
Accept: application/json