### Gets all the values
GET {{host}}/data/list

### Sets the value 1
PUT {{host}}/data/name
Content-Type: application/json

{
  "value": "The example name"
}

### Sets the value 2
PUT {{host}}/data/description
Content-Type: application/json

{
  "value": "This is the testing description"
}

### Gets the value
GET {{host}}/data/name

### Removes the value
DELETE {{host}}/data/name